---
- name: Automated Deployment and Configuration with Ansible
  hosts: hng
  become: yes
  vars:
    pg_password_file: /var/secrets/pg_pw.txt
    pg_user: postgres
    pg_password: securepassword
    pg_database: postgres
    pg_host: localhost
    app_port: 3000
    app_dir: /opt/stage_5b
    log_dir: /var/log/stage_5b

  tasks:
    - name: Ensure hng user exists
      user:
        name: hng
        state: present
        groups: sudo

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        owner: hng
        mode: '0755'
      loop:
        - /var/secrets
        - "{{ log_dir }}"

    - name: Save PostgreSQL admin credentials
      copy:
        dest: "{{ pg_password_file }}"
        content: "PG_USER={{ pg_user }}\nPG_PASSWORD={{ pg_password }}\nPG_DATABASE={{ pg_database }}\n"
        owner: root
        group: root
        mode: '0600'

    - name: Read PostgreSQL credentials
      slurp:
        src: "{{ pg_password_file }}"
      register: pg_creds

    - name: Set PostgreSQL credentials as variables
      set_fact:
        pg_user: "{{ (pg_creds.content | b64decode).split('\n')[0].split('=')[1] }}"
        pg_password: "{{ (pg_creds.content | b64decode).split('\n')[1].split('=')[1] }}"
        pg_database: "{{ (pg_creds.content | b64decode).split('\n')[2].split('=')[1] }}"

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - git
          - postgresql
          - nginx
          - rabbitmq-server
          - golang
        state: present

    - name: Mark repository directory as safe
      shell: git config --global --add safe.directory "{{ app_dir }}"
      args:
        executable: /bin/bash

    - name: Clone or update the repository
      git:
        repo: https://github.com/hngprojects/hng_boilerplate_golang_web.git
        dest: "{{ app_dir }}"
        version: devops
        update: yes
        accept_hostkey: yes
        force: yes

    - name: Ensure app directory is owned by hng user
      file:
        path: "{{ app_dir }}"
        owner: hng
        group: hng
        recurse: yes
        
    - name: Create app.env file
      copy:
        dest: "{{ app_dir }}/app.env"
        content: |
          SERVER_PORT=3000
          SERVER_SECRET="mySecretKey"
          SERVER_ACCESSTOKENEXPIREDURATION=2
          REQUEST_PER_SECOND=6
          TRUSTED_PROXIES=["192.168.0.1", "192.168.0.2"]
          EXEMPT_FROM_THROTTLE=["127.0.0.1", "192.168.0.2", "::1"]

          DB_HOST=localhost
          DB_PORT=5432
          DB_CONNECTION=pgsql
          TIMEZONE=Africa/Lagos
          SSLMODE=disable
          USERNAME=postgres
          PASSWORD=securepassword
          DB_NAME=postgres
          MIGRATE=false
        owner: hng
        group: hng
        mode: '0600'

    - name: Install application dependencies
      shell: |
        cd {{ app_dir }}
        go mod tidy
      args:
        chdir: "{{ app_dir }}"
      become: yes
      become_user: hng

    - name: Ensure application runs on port 3000
      shell: |
        cd {{ app_dir }}
        nohup go run main.go > {{ log_dir }}/out.log 2> {{ log_dir }}/error.log &
      args:
        chdir: "{{ app_dir }}"
      become: yes
      become_user: hng

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "0644"
      notify: Reload Nginx

    - name: Ensure log files are owned by hng user
      file:
        path: "{{ item }}"
        owner: hng
        group: hng
        state: touch
        mode: '0644'
      loop:
        - "{{ log_dir }}/error.log"
        - "{{ log_dir }}/out.log"

    - name: Ensure services are running
      service:
        name: "{{ item }}"
        state: started
      loop:
        - postgresql
        - nginx
        - rabbitmq-server

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Reload Environment
      shell: |
        if [ -f /etc/environment ]; then
          . /etc/environment
        fi
      args:
        executable: /bin/bash
